wg genkey | tee cle-priv | wg pubkey | tee cle-pub

[Interface]
PrivateKey = PRIVATE_KEY
Address = 10.0.0.1/24

[Peer]
PublicKey = PUBLIC_KEY
EndPoint = xxx.xxx.xxx.xxx:ppppp
AllowedIPs = 10.0.0.2/32
PersistentKeepAlive = 25    